apiVersion: v1
kind: Service
metadata:
  name: services-notes-app
  namespace: nginx
spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP